/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

public class Vetor {
    int elementos[];

    Vetor() {

    }

    Vetor(int _tamanho) {
        elementos = new int[_tamanho];
    }

    public void inserir(int _valor) {
        /**
         * [v1,v2,v3,v4] [0,0,0,0,0] +1 [0,0,0,0,0] x2 [0,0,0,0,0] ^2
         * 
         */
    }

}
