/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import org.junit.Test;
import static org.junit.Assert.*;

public class ListaTest {
    @Test
    public void testInserirUmElemento() {
        // montar o cenário
        ListaCircular lista = new ListaCircular();

        // faz a ação
        lista.adicionar(1);

        // executa o teste
        assertEquals(1, lista.getTamanho());
    }

    @Test
    public void testInserirDoisElementos() {
        ListaCircular lista = new ListaCircular();

        lista.adicionar(1);
        lista.adicionar(2);

        assertEquals(2, lista.getTamanho());
        assertEquals(2, lista.get(1));
    }

    @Test
    public void testRemoverUmElemento() {
        ListaCircular lista = new ListaCircular();
        lista.adicionar(1);
        lista.adicionar(2);
        lista.adicionar(3);
        lista.adicionar(4);

        lista.remover(3);

        assertEquals(3, lista.getTamanho());
        assertEquals(4, lista.get(2));
    }

}
